### ISSUE TITLE
Why expose Internal template ID?

### ISSUE THREAD

**Issue by samrocketman** [KostyaSha/yet-another-docker-plugin#160]
Upgraded to `0.1.0-rc36` to check out the latest changes.  Why does YADP Docker Template settings expose `Internal template ID`?  I can't edit it so it doesn't make much sense to expose it from what I can tell.

![screenshot reference](https://cloud.githubusercontent.com/assets/875669/25780069/3e716b6a-32d7-11e7-9359-940f75ce3a2b.png)

**Comment by KostyaSha** [comment]
That was initial idea to make templates separately from Cloud object and then use them. For this i needed storage, that needs some ids. Later i found that it wouldn't work in practise because templates has counters that usually specific to cloud. But this id was useful to clearly identify configuration:
- have multiple templates with the same docker image (docker-plugin probably is still limited lol)
- on page reconfigurations this template always is those that user created, it should be used for counters calculations. But here probably there is a problem that Cloud object itself will be recreated and loose counters.
- without this id it maybe unclear for what the same docker image what template user configure.

**Comment by samrocketman** [comment]
Ok, I was mostly curious.  It doesn't negatively affect me in any way.  Thanks for your answer.
