### ISSUE TITLE
Credentials Not Selected after upgrading to 0.1.4

### ISSUE THREAD

**Issue by eliasbalasis** [KostyaSha/yet-another-docker-plugin#276]
We have updated to Yet Another Docker 0.1.4

This resolved former issue with broken SSH Slaves binary compatibility (#275) but the "Credentials" drop down for "Docker SSH computer launcher" launch method is never accepting the chosen value, it always reverts to an arbitrary selection.

the <credentialsId> element in config is alsoset accordingly, not to the selected credentials ID though

**Comment by eliasbalasis** [comment]
If it helps you, we had to manually edit the config.xml, assign the correct value and reload.

We haven't tried resetting again though from configuration page, in fear it will start malfunctioning.

**Comment by eliasbalasis** [comment]
Some more feedback,
every time we change anything in configuration the credentials are getting lost from config.xml

**Comment by 33man** [comment]
Same here. I keep SSH Slaves plugin to 1.29.4 as the 1.31.0 breaks this plugin but the 0.1.4 is definitely not storing credentials. 

I use groovy scripts to configure jenkins so at every reboot it rollbacked to expected state if someone plays around with the settings. But so far : 

`
      SSHConnector sshConnector = new SSHConnector(obj.optInt('launch_ssh_port', 22),
          obj.optString('launch_ssh_credentials_id'),
          obj.optString('launch_ssh_prefix_start_slave_command'),
          obj.optString('launch_ssh_suffix_start_slave_command'),
          obj.optInt('launch_ssh_connection_timeout'),
          obj.optInt('launch_ssh_max_num_retries'),
          obj.optInt('launch_ssh_time_wait_between_retries')
      )
      return new DockerComputerSSHLauncher(sshConnector)
`

has definitely changed : https://github.com/KostyaSha/yet-another-docker-plugin/compare/0.1.3...master#diff-18e1cc7bbe4c4d6477b7e68f87e8bdbf 

And i was using User/password style credentials to connect to slave, where I'm wondering : https://github.com/KostyaSha/yet-another-docker-plugin/compare/0.1.3...master#diff-18e1cc7bbe4c4d6477b7e68f87e8bdbfR236-R238 seems to return only SSH_SCHEME from credentials provider ?

So are we forced now to use key + cert from credential provider instead of username password ?

**Comment by KostyaSha** [comment]
The problem is that selected creds where not saved, prepared fix. Tested manually in UI.

**Comment by eliasbalasis** [comment]
Thanks for fixing this.

Are you planning to release 0.1.5?
