### ISSUE TITLE
Support Docker Compose

### ISSUE THREAD

**Issue by skahlhoefer** [KostyaSha/yet-another-docker-plugin#45]
Hi @KostyaSha,

thanks a lot for your work. We are pretty close to migrating from the original Docker Plugin to your YADP and waiting for the YADP to reach a stable release.

Unfortunately we currently have a quite big need to integrate Docker Compose within our Jenkins CI environment as we have to deploy into a container with an individual database container linked.
So could you please implement support for Docker Compose soon?

That would be awesome and make you my personal hero! :-)

Cheers,
Stefan

**Comment by KostyaSha** [comment]
Frankly speaking i can't imagine how it should even work. docker-compose is just a binary that talks with daemon and spins containers. jenkins plugin is working via api with docker or swarm... What you can easily do it run docker-compose as job step, because jov environment already has all docker vars injected. So that would spin additional container.

What is also interesting - it's stacks. 
Please share some use case.

> to reach a stable release.

I think it already more stable than other released jenkins plugins. I will change versioning after moving to https://github.com/jucies/releases   you can think about rc's like minor-patch versions.
